#!/usr/bin/env bash

export FZF_DEFAULT_OPTS="--reverse --border=sharp --border-label=' tmux switch session ' --border-label-pos=-2 --info=right --no-scrollbar"

tmuxsessions=$(tmux list-sessions -F "#{session_name}")

tmux_switch_to_session() {
    session="$1"
    if [[ $tmuxsessions = *"$session"* ]]; then
        tmux switch-client -t "$session"
    fi
}

choice=$(echo "$tmuxsessions" \
    | fzf \
    | tr -d '\n')
tmux_switch_to_session "$choice"
