return {
  -- 'stevearc/oil.nvim',
  -- dependencies = { 'nvim-tree/nvim-web-devicons' },
  -- config = function()
  --   require('oil').setup({
  --     use_default_keymaps = false,
  --     keymaps = {
  --       ['g?'] = 'actions.show_help',
  --       ['<CR>'] = 'actions.select',
  --       ['<C-v>'] = 'actions.select_vsplit',
  --       ['<C-s>'] = 'actions.select_split',
  --       ['<C-t>'] = 'actions.select_tab',
  --       ['<C-p>'] = 'actions.preview',
  --       ['<C-c>'] = 'actions.close',
  --       ['<C-r>'] = 'actions.refresh',
  --       ['-'] = 'actions.parent',
  --       ['_'] = 'actions.open_cwd',
  --       ['`'] = 'actions.cd',
  --       ['~'] = 'actions.tcd',
  --       ['gs'] = 'actions.change_sort',
  --       ['gx'] = 'actions.open_external',
  --       ['g.'] = 'actions.toggle_hidden',
  --       ['g\\'] = 'actions.toggle_trash',
  --     },
  --     view_options = {
  --       show_hidden = true,
  --     },
  --   })
  --
  --   vim.keymap.set({ 'n', 'v' }, '<leader>o', require('oil').open, { desc = 'Open Oil' })
  -- end,
}
